// <auto-generated />
using System;
using Convention.Service.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Convention.Service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818201125_AddConventionOwnershipScoping")]
    partial class AddConventionOwnershipScoping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Convention.Service.Models.Convention", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CheminPdf")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateGeneration")
                        .HasColumnType("date");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<long?>("EncadrantId")
                        .HasColumnType("bigint");

                    b.Property<string>("StagiaireEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("StagiaireId")
                        .HasColumnType("uuid");

                    b.Property<string>("StagiaireNom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StagiairePrenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StatutSignature")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long?>("UtilisateurId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EncadrantId");

                    b.HasIndex("StagiaireId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Conventions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
