using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging;

namespace Smartek.Common.Middleware;

/// <summary>
/// Reads the <c>X-Trace-Id</c> header (generated by the API gateway's
/// <c>TraceIdFilter</c>) and sets it as the ASP.NET Core <c>TraceIdentifier</c>.
///
/// Also opens a logging scope so every log line written during this request
/// carries the trace ID, making it trivial to grep one ID across all service
/// logs and trace a request end-to-end.
///
/// If no header is present (e.g. a direct call to a service port), a new GUID
/// is generated so the trace identifier is never empty.
/// </summary>
public sealed class TraceIdMiddleware
{
    private const string HeaderName = "X-Trace-Id";
    private readonly RequestDelegate _next;

    public TraceIdMiddleware(RequestDelegate next)
    {
        _next = next;
    }

    public async Task InvokeAsync(HttpContext context)
    {
        if (context.Request.Headers.TryGetValue(HeaderName, out var traceId)
            && !string.IsNullOrWhiteSpace(traceId))
        {
            context.TraceIdentifier = traceId!;
        }

        // Every log line written inside this scope will carry TraceId=<id>.
        using var scope = BeginLoggingScope(context);
        await _next(context);
    }

    private static IDisposable BeginLoggingScope(HttpContext context)
    {
        // Use ILogger to create a scope — this is the idiomatic ASP.NET Core way.
        var loggerFactory = context.RequestServices.GetRequiredService<ILoggerFactory>();
        var logger = loggerFactory.CreateLogger("Smartek.Tracing");
        return logger.BeginScope(new Dictionary<string, object?>
        {
            ["TraceId"] = context.TraceIdentifier,
            ["Method"] = context.Request.Method,
            ["Path"] = context.Request.Path.Value
        });
    }
}
