apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gestion-stagiaires-ingress
  namespace: gestion-stagiaires-stb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: stb.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8080