using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Stagiaire.Service.Data;

#nullable disable

namespace Stagiaire.Service.Migrations;

// These attributes are how EF discovers a migration. They were missing (this file was written by
// hand rather than generated by `dotnet ef migrations add`), so the migrator found zero migrations,
// silently reported "up to date", and never created the database — every request then failed with
// 3D000: database "stagiaire_service_db" does not exist.
[DbContext(typeof(AppDbContext))]
[Migration("20260714000000_InitialCreate")]
public partial class InitialCreate : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Stagiaires",
            columns: table => new
            {
                Id = table.Column<Guid>(type: "uuid", nullable: false),
                Nom = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                Prenom = table.Column<string>(type: "character varying(100)", maxLength: 100, nullable: false),
                Email = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: false),
                Departement = table.Column<string>(type: "character varying(150)", maxLength: 150, nullable: false),
                DateDebut = table.Column<DateOnly>(type: "date", nullable: false),
                DateFin = table.Column<DateOnly>(type: "date", nullable: false),
                Statut = table.Column<string>(type: "character varying(20)", maxLength: 20, nullable: false)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Stagiaires", x => x.Id);
            });

        migrationBuilder.CreateIndex(
            name: "IX_Stagiaires_Email",
            table: "Stagiaires",
            column: "Email",
            unique: true);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.DropTable(
            name: "Stagiaires");
    }
}